apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fe-dep
  name: fe-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fe-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fe-dep
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - operator: In
                    key: app
                    values:
                      - fe 
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
