apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fe 
  name: fe 
spec:
  containers:
  - image: httpd
    name: fe 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - operator: In 
              key: app
              values:
                - fe 
status: {}
