apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sleep-dep
  name: sleep-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sleep-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sleep-dep
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                    - fe
                    - be
      containers:
      - image: itisfoundation/sleeper
        name: sleeper
        resources: {}
status: {}
