apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: expose-nginx
  name: expose-nginx
spec:
  ports:
  - name: 80-30001
    port: 8081
    nodePort: 30001
    protocol: TCP
    targetPort: 80 
  selector:
    app: my-ng 
  type: NodePort
status:
  loadBalancer: {}
