apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-ng
  name: my-ng
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-ng
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-ng
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {} 
status: {}
