---

- hosts: all
  gather_facts: true

  vars:
    my_color_choice: blue
  
  collections:
    - local.colors

  tasks:
    - name: "Verify {{ my_color_choice }} is a form of blue."
      assert:
        that: my_color_choice is blue