---
- hosts: rhelHost
  gather_facts: true
  become: True

  pre_tasks:
    # - include_vars:
    #   - "{{ ansible_os_family }}_vars.yml"
    #   - "{{ ansible_os_family }}_vars.yml"
    - include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_os_family }}_vars.yml"
        - "{{ ansible_os_family }}_vars.yml"

  tasks:
    - name: Install Apache
      package:
        name: "{{ apache_service_name }}"
        state: present

    - name: restart Appache and make sure runs at startup
      service:
        name: "{{ apache_service_name }}"
        state: started
        enabled: True

    - name: Print the OS Family for each of the OSs
      ansible.builtin.debug:
        var: ansible_os_family
    
    