---

- hosts: all
  become: true
  vars:
    ansible_install_method: package 
    firewall_allowed_tcp_ports:
      - "22"
      - "8080"
    jenkins_plugins:
      - ansicolor
  
  pre_tasks:
    - name: update the cache
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - geerlingguy.firewall
    - geerlingguy.pip
    - geerlingguy.ansible
    - geerlingguy.java
    - geerlingguy.jenkins

