apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ng-svc
  name: ng-svc
spec:
  ports:
  - name: my-ng-svc 
    nodePort: 30000
    port: 4040
    protocol: TCP
    targetPort: 80
  selector:
    app: ng-dep
  type: NodePort
status:
  loadBalancer: {}
