apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fe-app-r
  name: fe-app
spec:
  tolerations:
  - operator: "Exists"
    key: "app"
    effect: "NoSchedule"
  containers:
  - image: httpd
    name: fe-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: wn2-k8s
status: {}
