apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-dep
  name: test-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: test-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-dep
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - operator: "Equal"
        effect: "NoExecute"
        key: "app"
        value: "fe"
      containers:
      - image: httpd 
        name: alpine
        resources: {}
status: {}
