apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  ports:
  - name: port 
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    rs-label: labeled
  type: LoadBalancer
status:
  loadBalancer: {}
