---

- hosts: all
  become: true

  vars_files:
    - vars/vars.yml
  
  roles:
    - geerlingguy.git
    - geerlingguy.nodejs
    - geerlingguy.ruby
    - geerlingguy.passenger
  
  tasks:
    - name: Install app dependicies.
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - libsqlite3-dev
        - libreadline-dev
        - tzdata
    
    - name: Ensure app directory exists and is writeable
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0755
