apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-dep
  name: test-dep
spec:
  replicas: 20
  selector:
    matchLabels:
      app: test-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: 1Gi
            cpu: 1
status: {}
