apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-svc
  name: my-svc
spec:
  ports:
  - name: port-mapping
    port: 1414
    protocol: TCP
    targetPort: 80 
  selector:
    app: front-end 
  type: LoadBalancer
status:
  loadBalancer: {}
