apiVersion: v1
kind: LimitRange
metadata:
  name: ns-lr
  namespace: third-ns
spec:
  limits:
    - default:
        cpu: 312m
        memory: 312Mi
      defaultRequest:
        cpu: 230m
        memory: 230M
      min:
        cpu: 100m
        memory: 100Mi
      max:
        cpu: 500m
        memory: 500Mi
      type: Container
