apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-svc
  name: app-svc
spec:
  ports:
  - name: 80-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: color-app

  type: LoadBalancer
status:
  loadBalancer: {}
