apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app-red

spec:
  replicas: 10
  selector:
    matchLabels:
      app: red-color-app
  template:
    spec:
      containers:
        - image: mmumshad/simple-webapp-color
          name: color-app
          ports:
            - containerPort: 8080
          env:
          - name: APP_COLOR
            value: "green"
          - name: APP_MODE
            value: "prod"
    metadata:
      labels:
        app: red-color-app
