apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: np-svc
  name: np-svc
spec:
  ports:
  - name: 31001-5678
    port: 31001
    protocol: TCP
    targetPort: 80
    nodePort: 31002
  selector:
    app: c-ip 
  type: NodePort
status:
  loadBalancer: {}
