apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ht-dep
  name: ht-dep
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ht-dep
  strategy: 
    type: Recreate 
    #   rollingUpdate:
    #  maxSurge: 10% 
    #  maxUnavailable: 10%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ht-dep
    spec:
      containers:
      - image: redis 
        name: httpd
        resources: {}
status: {}
