apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pp-svc
  name: pp-svc
spec:
  ports:
  - name: 2450-80
    nodePort: 30002
    port: 2450
    protocol: TCP
    targetPort: 80
  selector:
    app: pp-dep
  type: NodePort
status:
  loadBalancer: {}
