---

- hosts: all
  gather_facts: no
  
  vars:
    should_fail_via_fail: false 
    should_fail_via_assert: flase
    should_fail_via_complex_assert: false

  tasks:
    - name: Fail if condition warrant a filure
      fail:
        msg: "There was an epic failue."
      when: should_fail_via_fail

    - name: Stop playbook if an assertion is'nt validated
      assert:
        that: "should_fail_via_assert != true"

    - name: Assertion can have contain conditions
      assert:
        that:
          - should_fail_via_fail != true
          - should_fail_via_assert != true
          - should_fail_via_complex_assert != true 
