---

- hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update Cache.
      apt:
        update_cache: true
        cache_valid_time: 3600
  
  tasks:
    - name: Install Java.
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Download Solr.
      get_url:
        url: "https://archive.apache.org/dist/lucene/solr/\
        {{ solr_versoin }}/solr-{{ solr_versoin }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_versoin }}.tgz"
        checksum: "{{ solr_checksum }}"
    - name: Expand Solr.
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_versoin }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_versoin }}/README.txt"
    - name: Run Solr installation script.
      command: >
        {{ download_dir }}/solr-{{ solr_versoin }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_versoin }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p {{ solr_port }}
        creates={{ solr_dir }}/bin/solr
    - name: Ensure solr is started and enabled on boot
      service:
        name: solr
        state: started
        enabled: true