apiVersion: v1
kind: LimitRange
metadata:
  name: ht-app
  namespace: lr-test
spec:
  limits:
    - default:
        cpu: 512m
      defaultRequest:
        cpu: 256m
      min:
        cpu: 128m
      max:
        cpu: 514m
      type: Container
