apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
    app: fe
  name: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx
  nodeName: ip-172-31-3-99.ec2.internal
