apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dev-dep
  name: dev-dep
  namespace: dev
spec:
  replicas: 15
  selector:
    matchLabels:
      app: dev-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dev-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
