---

- hosts: all
  become: true
  
  vars:
    build_root: /vagrant/provisioning
  
  pre_tasks:
    - name: Update the cache
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: geerlingguy.docker
  
  tasks:
    - import_tasks: setup.yml
    - import_tasks: docker.yml