apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tt-dep
  name: tt-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tt-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tt-dep
    spec:
      containers:
      - image: alpine:edge
        name: alpine
        resources: 
          limits:
            cpu: 100m 
            memory: 312M
status: {}
