apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-web-app
  name: svc-web-app
spec:
  ports:
  - name: 4040-80
    port: 4040
    protocol: TCP
    targetPort: 8080
  selector:
    app: s-web-app
  type: NodePort
status:
  loadBalancer: {}
