apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: be-dep
  name: be-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: be-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: be-dep
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: app
                    operator: Exists
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: NotIn
                    values:
                      - fe
      containers:
      - image: redis
        name: redis
        resources: {}
status: {}
