apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fe
  name: fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fe
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: app
                    operator: NotIn
                    values:
                      - be 
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fe  
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
