apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: dev
spec: {}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
spec: 
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi 
