apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fe

  template:
    spec:
      containers:
        - image: nginx:latest
          name: my-cont
    metadata:
      labels:
        app: fe

